export const FETCH_PROPERTIES = "FETCH_PROPERTIES";
export const FETCH_PROPERTIES_SUCCESS = "FETCH_PROPERTIES_SUCCESS";
export const FETCH_PROPERTIES_FAILURE = "FETCH_PROPERTIES_FAILURE";
export const FETCH_DETAILS = "FETCH_DETAILS";
export const FETCH_DETAILS_SUCCESS = "FETCH_DETAILS_SUCCESS";
export const FETCH_DETAILS_FAILURE = "FETCH_DETAILS_FAILURE";
